name: Build Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      GRADLE_VERSION: 7.5.1
      GRADLE_HOME: /usr/share/gradle-7.5.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Display JAVA_HOME
      run: echo $JAVA_HOME

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3
        ndk: 21.4.7075529

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
        unzip gradle-7.5.1-bin.zip
        sudo mv gradle-7.5.1 /usr/share/gradle-7.5.1

    - name: Add Gradle to PATH
      run: echo "$GRADLE_HOME/bin" >> $GITHUB_PATH

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: npm install

    - name: Decode and set up keystore
      run: |
        mkdir -p android/app
        echo ${{ secrets.ANDROID_KEYSTORE_BASE64 }} | base64 --decode > android/app/my-upload-key.keystore

    - name: Start Metro Bundler
      run: yarn start &
      env:
        CI: true

    - name: Build Android
      run: cd android && ./gradlew assembleRelease
      env:
        CI: true
        JAVA_HOME: ${{ env.JAVA_HOME }}
        ANDROID_HOME: /usr/local/lib/android/sdk
        GRADLE_HOME: /usr/share/gradle-7.5.1
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk